version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  redisCommander:
    image: rediscommander/redis-commander
    ports:
      - "9081:8081"
    environment: 
      - REDIS_HOST=redis
    depends_on: 
      - redis

  matchmaker:
    image: optimuscloud/match-maker
    restart: always
    ports:
      - "6898:6898"

  mdb:
    image: optimuscloud/mdb
    restart: always
    ports:
      - "9099:9099"

  akira:
    image: optimuscloud/akira
    ports:
      - "6889:6889"
    restart: always
    environment: 
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - SESSION_TIMEOUT=15
    depends_on:
      - rabbitmq
      - redis
      - matchmaker

  mongo:
    image: mongo
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=optimus
    ports:
      - "27017:27017"

  optimusUsers:
    image: testvagrant/optimususers
    restart: always
    environment:
      - DB_NAME=optimus
      - DB_SERVER_URL=mongo:27017
    depends_on: 
      - mongo

  optimusServices:
    image: testvagrant/optimus-services
    ports:
      - "8090:8093"
    environment:  
      - database=optimus
      - uri=mongodb://mongo:27017
      - port=8093
    restart: always
    depends_on:
        - mongo

  optimusDashboard:
    image: testvagrant/optimusdashboard
    ports:
      - "9901:9900"
    environment:
      - DE_ENV=production
      - DB_SERVER_URL=mongo:27017
      - DB_NAME=optimus?authSource=admin
    restart: always
    depends_on:
        - mongo

  hoarder:
    image: optimuscloud/hoarder
    ports:
      - "6090:6090"
    environment:
      - database=optimus
      - uri=mongodb://mongo:27017
      - port=6090
    restart: always
    depends_on:
      - mongo
